version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: docker.io/bitnami/redis:6.0
    volumes:
      - 'redis_data:/bitnami'
      - ./workspace/airflow/dags:/opt/bitnami/airflow/dags
      - ./workspace/airflow/plugins:/opt/bitnami/airflow/plugins
      - ./workspace/airflow/create_tables.sql:/opt/bitnami/airflow/create_tables
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  airflow-scheduler:
    # TODO: to be reverted to use proper registry/distro on T39132
    # image: docker.io/bitnami/airflow-scheduler:1
    image: docker.io/bitnami/airflow-scheduler:1
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
    volumes:
      - airflow_scheduler_data:/bitnami
      - ./workspace/airflow/dags:/opt/bitnami/airflow/dags
      - ./workspace/airflow/plugins:/opt/bitnami/airflow/plugins
      - ./workspace/airflow/create_tables.sql:/opt/bitnami/airflow/create_tables
  airflow-worker:
    # TODO: to be reverted to use proper registry/distro on T39132
    # image: docker.io/bitnami/airflow-worker:1
    image: docker.io/bitnami/airflow-worker:1
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
    volumes:
      - airflow_worker_data:/bitnami
      - ./workspace/airflow/dags:/opt/bitnami/airflow/dags
      - ./workspace/airflow/plugins:/opt/bitnami/airflow/plugins
      - ./workspace/airflow/create_tables.sql:/opt/bitnami/airflow/create_tables
  airflow:
    image: docker.io/bitnami/airflow:1
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_USERNAME=user
      - AIRFLOW_PASSWORD=bitnami
    ports:
      - '8080:8080'
    volumes:
      - airflow_data:/bitnami
      - ./workspace/airflow/dags:/opt/bitnami/airflow/dags
      - ./workspace/airflow/plugins:/opt/bitnami/airflow/plugins
      - ./workspace/airflow/create_tables.sql:/opt/bitnami/airflow/create_tables
volumes:
  airflow_scheduler_data:
    driver: local
  airflow_worker_data:
    driver: local
  airflow_data:
    driver: local
  postgresql_data:
    driver: local
  redis_data:
    driver: local