version: '3.9'
services:
  jupyter-notebooks:
    network_mode: host
    build: .
    environment:
      JUPYTER_ENABLE_LAB: 'yes' #use jupyter lab, check https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html#docker
    volumes:
      - .:/home/jovyan/work



