version: '3.9'
services:
  db:
    network_mode: host #use host network so this can be seen as localhost
    image: library/postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: studentdb
  jupyter-notebooks:
    network_mode: host
    depends_on:
      - db
    build: .
    environment:
      JUPYTER_ENABLE_LAB: 'yes' #use jupyter lab, check https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html#docker
    volumes:
      - .:/home/jovyan/work



