version: '3.9'
services:
  db:
    image: library/postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: studentdb
  jupyter-notebooks:
    depends_on:
      - db
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work



