version: '3.9'
services:
  db:
    image: library/cassandra:3
    restart: always
  jupyter-notebooks:
    depends_on:
      - db
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work



